// <auto-generated />
using System;
using LpSync.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LpSync.Migrations
{
    [DbContext(typeof(LpSyncContext))]
    partial class LpSyncContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LpSync.Models.Acceso", b =>
                {
                    b.Property<string>("AccesoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AccesoID");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("UsuariaDiscogsUsername");

                    b.HasKey("AccesoID");

                    b.HasIndex("UsuariaDiscogsUsername");

                    b.ToTable("Acceso");
                });

            modelBuilder.Entity("LpSync.Models.Usuaria", b =>
                {
                    b.Property<string>("DiscogsUsername");

                    b.Property<bool>("EsHabilitada");

                    b.HasKey("DiscogsUsername");

                    b.ToTable("Usuaria");
                });

            modelBuilder.Entity("LpSync.Models.Acceso", b =>
                {
                    b.HasOne("LpSync.Models.Usuaria", "Usuaria")
                        .WithMany("Accesos")
                        .HasForeignKey("UsuariaDiscogsUsername");
                });
#pragma warning restore 612, 618
        }
    }
}
